export enum UserRole {
    MEMBER = 'MEMBER',
    MERCHANT_STAFF = 'MERCHANT_STAFF',
    MERCHANT_ADMIN = 'MERCHANT_ADMIN',
    SUPPORT = 'SUPPORT',
    ADMIN = 'ADMIN',
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}