<?php
return [
    'unitKeywords' => [
        'apt',
        'apartment',
        'unit',
        'ste',
        'bldg',
        'fl',
        'rm',
        '#',
    ],
    'directionMap' => [
        'N' => ['north', 'n', 'n.'],
        'S' => ['south', 's', 's.'],
        'E' => ['east', 'e', 'e.'],
        'W' => ['west', 'w', 'w.'],
        'NE' => ['northeast', 'ne', 'ne.'],
        'NW' => ['northwest', 'nw', 'nw.'],
        'SE' => ['southeast', 'se', 'se.'],
        'SW' => ['southwest', 'sw', 'sw.'],
    ],
    'suffixes' => [
        'Alley' => ['alley', 'aly'],
        'Avenue' => ['avenue', 'ave', 'av', 'ave.'],
        'Bayou' => ['bayou', 'byu'],
        'Beach' => ['beach', 'bch'],
        'Bend' => ['bend', 'bnd'],
        'Bluff' => ['bluff', 'blf'],
        'Boulevard' => ['boulevard', 'blvd'],
        'Bridge' => ['bridge', 'br', 'brdg'],
        'Brook' => ['brook', 'brk'],
        'Brooks' => ['brooks', 'brks'],
        'Bypass' => ['bypass', 'byp'],
        'Camp' => ['camp', 'cp'],
        'Canyon' => ['canyon', 'cyn'],
        'Cape' => ['cape', 'cpe'],
        'Causeway' => ['causeway', 'cswy'],
        'Center' => ['center', 'ctr'],
        'Circle' => ['circle', 'cir'],
        'Cliff' => ['cliff', 'clf'],
        'Club' => ['club', 'clb'],
        'Commons' => ['commons', 'cmns'],
        'Corner' => ['corner', 'cor'],
        'Court' => ['court', 'ct'],
        'Cove' => ['cove', 'cv'],
        'Creek' => ['creek', 'crk'],
        'Crescent' => ['crescent', 'cres'],
        'Crossing' => ['crossing', 'xing'],
        'Drive' => ['drive', 'dr'],
        'Expressway' => ['expressway', 'expy'],
        'Field' => ['field', 'fld'],
        'Flat' => ['flat', 'flt'],
        'Forest' => ['forest', 'frst'],
        'Fork' => ['fork', 'frk'],
        'Freeway' => ['freeway', 'fwy'],
        'Garden' => ['garden', 'gdn'],
        'Gateway' => ['gateway', 'gtwy'],
        'Glen' => ['glen', 'gln'],
        'Green' => ['green', 'grn'],
        'Grove' => ['grove', 'grv'],
        'Harbor' => ['harbor', 'hbr'],
        'Heights' => ['heights', 'hts'],
        'Highway' => ['highway', 'hwy'],
        'Hill' => ['hill', 'hl'],
        'Hollow' => ['hollow', 'holw'],
        'Island' => ['island', 'is'],
        'Junction' => ['junction', 'jct'],
        'Key' => ['key', 'ky'],
        'Knoll' => ['knoll', 'knl'],
        'Lake' => ['lake', 'lk'],
        'Lane' => ['lane', 'ln'],
        'Loaf' => ['loaf', 'lf'],
        'Lock' => ['lock', 'lck'],
        'Lodge' => ['lodge', 'ldg'],
        'Loop' => ['loop', 'lp'],
        'Manor' => ['manor', 'mnr'],
        'Meadow' => ['meadow', 'mdw'],
        'Mill' => ['mill', 'ml'],
        'Mission' => ['mission', 'msn'],
        'Mountain' => ['mountain', 'mtn'],
        'Park' => ['park', 'prk'],
        'Parkway' => ['parkway', 'pkwy'],
        'Pass' => ['pass', 'pss'],
        'Place' => ['place', 'pl'],
        'Plaza' => ['plaza', 'plz'],
        'Point' => ['point', 'pt'],
        'Port' => ['port', 'prt'],
        'Prairie' => ['prairie', 'pr'],
        'Ridge' => ['ridge', 'rdg'],
        'River' => ['river', 'riv'],
        'Road' => ['road', 'rd'],
        'Route' => ['route', 'rte'],
        'Square' => ['square', 'sq'],
        'Station' => ['station', 'sta'],
        'Street' => ['street', 'st'],
        'Summit' => ['summit', 'smt'],
        'Terrace' => ['terrace', 'ter'],
        'Trail' => ['trail', 'trl'],
        'Valley' => ['valley', 'vly'],
        'View' => ['view', 'vw'],
        'Village' => ['village', 'vlg'],
        'Way' => ['way', 'wy'],
        'Well' => ['well', 'wl'],
        'Wharf' => ['wharf', 'whf'],
        'Run' => ['run'],
        'Stream' => ['stream', 'strm'],
        'Stravenue' => ['stravenue', 'strav', 'strvn'],
        'Track' => ['track', 'trk', 'trks'],
        'Passage' => ['passage', 'psge'],
    ],
];
